# Generated by Django 6.0.5 on 2026-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='cp_type',
            field=models.CharField(choices=[('Type1', 'Report Type 1'), ('Type2', 'Report Type 2'), ('Type3', 'Report Type 3')], default='Type1', max_length=5),
        ),
    ]
