# Generated by Django 6.0.5 on 2026-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mouse', '0002_variety_cp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
